version: '3.8'

services:
  app:
    build: .
    container_name: gitguard-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    # We keep 'db' here just in case, but your app will connect to Atlas
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: gitguard-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: